# Generated by CodiumAI

from proj1.src.app.schemas import UserCreate

import pytest


class TestUserCreate:

    #  Validate that a valid email and password are accepted without errors
    def test_valid_email_and_password(self):
        # Given a valid email and password
        valid_email = "user@example.com"
        valid_password = "securepassword123"

        # When creating a UserCreate instance
        user = UserCreate(email=valid_email, password=valid_password)

        # Then no validation errors should occur
        assert user.email == valid_email
        assert user.password == valid_password

    #  Test with an invalid email format to ensure validation errors are raised
    def test_invalid_email_format(self):
        # Given an invalid email format and a valid password
        invalid_email = "useratexampledotcom"
        valid_password = "securepassword123"

        # When attempting to create a UserCreate instance
        with pytest.raises(ValueError) as exc_info:
            user = UserCreate(email=invalid_email, password=valid_password)

        # Then a validation error should be raised
        assert "value is not a valid email address" in str(exc_info.value)
