# Generated by CodiumAI

from proj1.src.app.schemas import PostCreate

import pytest


class TestContentMustNotBeEmpty:

    #  Method accepts content with non-whitespace characters
    def test_content_with_non_whitespace_characters(self):
        # Given: a valid content string with non-whitespace characters
        content = "Hello, world!"

        # When: creating a PostCreate object with this content
        post = PostCreate(title="Valid Title", content=content)

        # Then: no exception is raised and the content is correctly set
        assert post.content == content

    #  Method raises ValueError if content is an empty string
    def test_empty_content_raises_value_error(self):
        # Given: an empty content string
        content = ""

        # When & Then: creating a PostCreate object with empty content should raise ValueError
        with pytest.raises(ValueError) as exc_info:
            post = PostCreate(title="Valid Title", content=content)

        assert str(exc_info.value) == "Content must not be empty"
